version: '3.9'

services:
  backend:
    image: pekkalin/simple-express-app:latest
    ports:
      - '8080:8080'
    restart: unless-stopped
    container_name: simple-express-app

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
